
-- ユーザーテーブル --
CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	role VARCHAR(20) NOT NULL DEFAULT 'ROLE_USER'
);

-- スキルテーブル --
CREATE TABLE skills (
	id SERIAL PRIMARY KEY,
	user_id INT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id), 
	skill VARCHAR(255) NOT NULL UNIQUE
);